### ISSUE TITLE
Building Permits - Schedule Inspections Lookup Not Showing Unscheduled Inspections After Date has been Cleared

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#246]
This issue is written on behalf of Bob Ensor:

When creating a My Infor - ad hoc report of "BP Open Inspection Requests",  that is showing extra information than when querying / searching records via Building Inspection Lookup (for scheduled inspections).  Noting here the the Building Inspection Lookup seems to be more accurate.

Please see Bob Ensor for details and examples.

**Comment by JuanitaMiles** [comment]
Followed up on this issue with Bob. The issue appears to be when using the search functionality on the Schedule Inspections page is somehow not recognizing that the schedule date has been cleared out because the inspection has been requested for a different date. 

An example of this is Permit # 258647 - Inspection # 1063134. Susan F. entered a new Requested date in the back office, which causes the system to automatically clear the Scheduled Date. It appears that making the requested date change in the back office does not trigger a notification to the inspector. It only causes the inspection to drop off the inspectors work viewer in mobile. This inspection would not show up within the Schedule Inspections lookup when the "Unscheduled Only" box is checked. (Bob has since re-scheduled this inspection in order to get it on the schedule for tomorrow)

Ad Hoc is not the issue here, changing the name of the ticket...

Assigning to @calequin as Bob was previously working with Christian on this issue.

**Comment by calequin** [comment]
notification cancellation issue has been fixed in another ticket and needs promotion.
This issue is when an inspection is cancelled via rhythm the time stamp on the scheduled date clears out but the system still thinks a time is there. Therefore the schedule inspections does not detect this inspection as an unscheduled inspection. Notes by CA for tracking purposes only. Still working on issue

**Comment by calequin** [comment]
once tested please promoted the following:
BP_InspectionChangeofDates_BU
USE_InspectionChangeofDates_BU

**Comment by JuanitaMiles** [comment]
Reached out to Bob to test.

**Comment by JuanitaMiles** [comment]
Bob has confirmed it works. Test Accepted.

**Comment by JuanitaMiles** [comment]
Bob indicated this is still happening when the Request is cancelled on R4C. Including snippets of his email with examples.
![image](https://user-images.githubusercontent.com/31770504/73753886-64e63700-4731-11ea-83fa-fa38c80c5251.png)
![image](https://user-images.githubusercontent.com/31770504/73753911-74658000-4731-11ea-9b1a-a942fe77f4c6.png)
![image](https://user-images.githubusercontent.com/31770504/73753935-83e4c900-4731-11ea-8637-d6a2014a2cc4.png)

**Comment by calequin** [comment]
Added logic to clear the isscheduled flag whenever someone cancels online regardless of same day. Please test and once accepted promote the follwoing:
USE_InspectionChangeofDates_BU
BP_InspectionChangeofDates_BU

**Comment by JuanitaMiles** [comment]
Bob Confirmed test passed.

![image](https://user-images.githubusercontent.com/31770504/73954284-972d9b00-48cf-11ea-8eb6-ae324f49a9b0.png)

**Comment by calequin** [comment]
need to promote:
BP_ManageInspection_BUF
USE_InspectionChangeofDates_BU
BP_InspectionChangeofDates_BU

**Comment by calequin** [comment]
promoted on 2.9.2020
