### ISSUE TITLE
Planning - Bond Lookup - Formatting issue

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#411]
Project Number - All bonds I have accessed so far today 3306, 3307, 3761, 3764
Observed behavior - Blue Box around comments is covering the add and edit options in bond tracking details
Expected behavior - Blue Box should not cover the fields below it. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/74536203-931fff80-4f05-11ea-96a6-3b36bf8e2885.png)

**Comment by calequin** [comment]
fixed in prod and test.

**Comment by AReed327** [comment]
Verified Corrected - Already deployed to production. Closing ticket. AREED

**Comment by AReed327** [comment]
This is happening again. Format from Comments field under edit mode is covering Bond Tracking Details
![image](https://user-images.githubusercontent.com/58854333/81313299-b31f1500-9055-11ea-99cc-344074c1a607.png)

**Comment by AReed327** [comment]
Bond #3286

**Comment by megisys** [comment]
@AReed327 
![image](https://user-images.githubusercontent.com/47392306/81569272-0e5e4980-936d-11ea-94d0-e2f5179b6ce1.png)

I dont see the issue. Is this still happening..

**Comment by megisys** [comment]
Fixed in Production - As no Business disruption

**Comment by JuanitaMiles** [comment]
@AReed327 Please confirm formatting is fixed in production then close if satisfied.

**Comment by AReed327** [comment]
Added a new transaction and the formatting is still causing an issue. When you are in a bond and you save it at the top, then edit again, it seems to cause this issue.
![image](https://user-images.githubusercontent.com/58854333/81692673-c141ac80-942c-11ea-9fd0-439db9248a76.png)

**Comment by megisys** [comment]
We got it this time. Just had to move it further down the page as the elements above it can grow.

**Comment by AReed327** [comment]
This is not fixed. I also was not given the opportunity to retest.
![image](https://user-images.githubusercontent.com/58854333/82322565-b8108c80-99a4-11ea-9618-8ebc0b39e511.png)

**Comment by megisys** [comment]
Is this in Production AReed ? @AReed327

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/82324856-52260400-99a8-11ea-9607-90bc16ad0506.png)

**Comment by megisys** [comment]
@AReed327 - There is no change to the underlaying product. So these can be changed directly in production
