### ISSUE TITLE
Missing Official Issuance

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#414]
Missing the official issuance documents for ResUse and Demo permits. 

Called Tara this morning.

**Comment by TaraF** [comment]
This was an error in code - I fixed in Test.  Needs to be promoted to PROD asap. 

The formula for on demand report Building Permit - Official Issuance (Building Permit), Formula: AR_4

![image](https://user-images.githubusercontent.com/4104464/74655888-243be400-515b-11ea-9221-c73a8eb2e204.png)

![image](https://user-images.githubusercontent.com/4104464/74655927-36b61d80-515b-11ea-9f72-2ecf859e34ba.png)

**Comment by ABonomo21** [comment]
Will the correspondence still work even if it is not available on demand for printing?

**Comment by TaraF** [comment]
@ABonomo21  - yes, the only formula change was the on demand portion, totally separate from correspondence.

**Comment by awhite806** [comment]
we are still missing the official issuance for Res Use and Demos
![image](https://user-images.githubusercontent.com/58981029/74741234-6e3fcb00-522a-11ea-943b-e0553b6399e6.png)
![image](https://user-images.githubusercontent.com/58981029/74741275-81529b00-522a-11ea-8548-e31d68b311a2.png)

**Comment by calequin** [comment]
promoted on 2.18.2020
