### ISSUE TITLE
Applicants Unable to Upload Attachments - 14472633#

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#461]
Applicants should be able to upload additional attachments when the permit is in a Milestone of 
Awaiting Applicant Revisions, Awaiting Applicant Resubmit, and once it is issued to be able to complete a Change Request.

**Comment by JuanitaMiles** [comment]
@pooldaddy Please ensure the configuration on R4C for Building permits applications allows applicants to add attachments for the three scenarios indicated above. The "Issued" status would encompass the Inspections and Final Inspection milestones.

**Comment by pooldaddy** [comment]
Need more info. Apllication # and type, milestone, attachment type that failed etc.

**Comment by ABonomo21** [comment]
it is all a/p's within the building permit, use permit business license and trade license module 
there could be any number of additional attachments that need to be added by the applicant in order to provide the county with the accurate information to complete reviews. 

we also need to confirm the applicants cannot remove attachments. this should be done by back office staff only.

**Comment by megisys** [comment]
Emailed the County on this issue.. Need examples

**Comment by ABonomo21** [comment]
test permit 266746
at the applicant resubmit

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/76456419-554fb300-63ad-11ea-8063-d6c9b51cb44e.png)

**Comment by megisys** [comment]
Updates to  allow attachments during milestones which start with Awaiting. Also can add attachments once a permit has an issued date and time.

**Comment by JuanitaMiles** [comment]
Need to reopen ticket. There are widespread problems with applicants being able to upload attachments. These issues were both reported by customers in the production system and I have tested and replicated the issues in the test environments.

1) At initial application submission, documents are not uploading. A customer sent a picture of their screen with this error for their RESBLDG application and I have also replicated the issue in Test R4C for DEMO, ELECTRICAL, FIRE, and RESBLDG. The application will be submitted and ap number generated, but the attachments will not upload.
Customer photo from production site.
![image](https://user-images.githubusercontent.com/31770504/77582151-4856b780-6eb5-11ea-92b4-e281190db068.png)

2) Applicants are not able to upload attachments at the Awaiting Applicant Revisions milestone. This is the milestone following the Under Review stage. I have tested this issue on DEMO, ELECTRICAL, FIRE, and RESBLDG thus far. All have the same issue/error message.
![image](https://user-images.githubusercontent.com/31770504/77582374-a8e5f480-6eb5-11ea-88bb-722d0f7c1240.png)
![image](https://user-images.githubusercontent.com/31770504/77582400-b4d1b680-6eb5-11ea-8534-7cdb302d5923.png)
![image](https://user-images.githubusercontent.com/31770504/77582412-b8653d80-6eb5-11ea-932b-227276420561.png)

3) Applicants cannot upload attachments after a permit has been issued. I have tested this issue on DEMO, ELECTRICAL, FIRE, and RESBLDG thus far. All have the same issue/error message.
![image](https://user-images.githubusercontent.com/31770504/77582759-45a89200-6eb6-11ea-89a3-6a96dc8ec97f.png)
![image](https://user-images.githubusercontent.com/31770504/77582773-4b05dc80-6eb6-11ea-93e5-76bf3384b442.png)
![image](https://user-images.githubusercontent.com/31770504/77582780-50632700-6eb6-11ea-96c6-a416ef7de8df.png)

**Comment by megisys** [comment]
Hi @JuanitaMiles,

I see 2 issues here which i am going to track down.. The customers issue is not the same as you are reporting.. Look at their attachment names with . (Periods) The file can only have one as it will cause the system to think anything after it is an extention of a file.. So I need to submit a defect for that one..

I am testing the timing for the ones you created in test and will report back

Dan

**Comment by megisys** [comment]
@JuanitaMiles  Made a change to the overall building permit piece.. Please test it out.. Now will not allow any updates unless. In a milestone starting with Application or Awaiting or issued

**Comment by JuanitaMiles** [comment]
Tested Demo 266779

1) Used an attachment that didn't have any weird or special characters and still got the error at initial submission.
![image](https://user-images.githubusercontent.com/31770504/77596676-0e94a980-6ed3-11ea-8264-e443ad771962.png)

2) Was able to upload at Awaiting Applicant Resubmit (Completeness check resubmit) but the system significantly changed the name of my file. Why would that happen?
![image](https://user-images.githubusercontent.com/31770504/77597084-20c31780-6ed4-11ea-8954-b7c0a58495e7.png)

3) Successfully uploaded attachment at Awaiting Applicant Revisions (under review resubmit) and when it was in an Issued status.

**Comment by megisys** [comment]
@JuanitaMiles , it is renaming it because. A file with that name already exists that the county has taken in and you can not have 2 files with the same name in the same place.

**Comment by megisys** [comment]
Xtreme ticket added for new submission with exisiting filename. Other problems i have addressed in code.

**Comment by megisys** [comment]
@JuanitaMiles Please Test on a Building Application.. With the same files as prior. If happy I will adjust across the board. The change is.. That attachments can be added to an application for 2 minutes from initial submission before locking the process.

**Comment by pooldaddy** [comment]
@megisys @JuanitaMiles  Just my 2 cents but given the extreme amount of internet traffic and not knowing how good our customers connection is.  Should we consider making the time greater.  Your thoughts?

**Comment by megisys** [comment]
Everything else would time out before this would hit

**Comment by JuanitaMiles** [comment]
Tested on a Demo permit 266786.

File successfully uploaded at the time of submitting the application. 

The file name changing is still an issue when I click the number to view the details of the application, but it appears that is waiting for Infor Xtreme. Just to be clear, I understand the need for a number to be placed at the end of duplicated file names, however in this instance it's cutting off part of the name instead of simply adding a number at the end.

File name at the "Confirmation" stage.
![image](https://user-images.githubusercontent.com/31770504/78046005-a4518e00-7344-11ea-9adf-a68e2cead23e.png)

File name when I click into the application to view it's information.
![image](https://user-images.githubusercontent.com/31770504/78046147-cb0fc480-7344-11ea-8ec8-d4c045cbef9b.png)

**Comment by JuanitaMiles** [comment]
Also, what is this new section on the attachment upload window? Should this checkbox be selectable by an applicant?
![image](https://user-images.githubusercontent.com/31770504/78046276-f5618200-7344-11ea-8fe8-5091a849b1c6.png)

**Comment by JuanitaMiles** [comment]
From the previous testing completed and this testing it appears the points where we were having issues uploading have been addressed. As long as the Attribute/Values table in the upload window could not potentially pose an issue if checked or unchecked, I'm generally comfortable pushing the fix to production.

Would like to perform more thorough testing of the overall process as time allows.

**Comment by megisys** [comment]
Deployed
